### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: ../models/ssd_mobilenet_v2_grocery_prod.config 

### ISSUE THREAD

**Issue by jennyrud01** [JoseAntonyS/SSD---Object-Detection-for-SuperMarket#1]
Hi Jose Antony 

While running start_train.sh file, I get this error message: tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: ../models/ssd_mobilenet_v2_grocery_prod.config : The system cannot find the file specified.

Traceback (most recent call last):
  File "model_main_tf2.py", line 115, in <module>
    tf.compat.v1.app.run()
  File "C:\Users\###\anaconda3\lib\site-packages\tensorflow_core\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\###\anaconda3\lib\site-packages\absl\app.py", line 303, in run
    _run_main(main, args)
  File "C:\Users\###\anaconda3\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "model_main_tf2.py", line 112, in main
    save_final_config=True)
  File "C:\Users\###\anaconda3\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\model_lib_v2.py", line 493, in train_loop
    pipeline_config_path, config_override=config_override)
  File "C:\Users\###\anaconda3\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\utils\config_util.py", line 138, in get_configs_from_pipeline_file
    proto_str = f.read()
  File "C:\Users\###\anaconda3\lib\site-packages\tensorflow_core\python\lib\io\file_io.py", line 122, in read
    self._preread_check()
  File "C:\Users\###\anaconda3\lib\site-packages\tensorflow_core\python\lib\io\file_io.py", line 84, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512)

It seems that the script fails to generate model configuration file. 
Have you had similar issues before? Any advice? 

Jenny

**Comment by JoseAntonyS** [comment]
Hi Jenny, use this  [config file](https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/ssd_mobilenet_v1_pets.config) and alter the parameters and paths to respective files. Later, copy the file in your working directory to start the training process.

**Comment by jennyrud01** [comment]
Thank you!
